server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://ubuntuserver.com:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    register-with-eureka: true  # 表示注册到 eurekaServer, 默认为 true
    fetch-registry: true  # 是否从 eurekaServer 抓取注册信息, 默认为 true, 单节点无所谓, 集群必须设置为 true, 才能配合 ribbon 使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka # 单机
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  # 集群

