server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.72.9
      port: 8600
      discovery:
        service-name: ${spring.application.name}