server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: ubuntuServer.com:8848  # nacos 服务注册中心地址
    sentinel:
      transport:
        dashboard: ubuntuServer.com:8080  # Sentinel Dashboard 地址
        port: 8719  # 默认8719端口, 假如端口被占用会自动从8719开始一次+1扫描, 直到找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: ubuntuServer.com:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule_type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"