server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: ubuntuServer.com:8848
    sentinel:
      transport:
        dashboard: ubuntuServer.com:8080  # Sentinel Dashboard 地址
        port: 8719  # 默认8719端口, 假如端口被占用会自动从8719开始一次+1扫描, 直到找到未被占用的端口
service-url:
  nacos-payment-service: http://nacos-payment-provider