server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka 服务端的实例名称
  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false # false 表示自己就是注册中心, 职责就是维护服务实例, 并不需要去检查服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ # 单纯设置
      # defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  # 设置与 eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
  # server:
    # enable-self-preservation: false # 关闭自我保护机制, 保证不可用服务立即剔除
    # eviction-interval-timer-in-ms: 2000